export const ANIMATION_DURATION = 150;

export const ACCOUNT_LIST_SKELETON_LENGTH = 8;

export const CURRENCY_MAX_RATE_LIST_LENGTH = 12;
export const CURRENCY_EXCHANGE_RATE_CHANGE_TYPE = 'EXCHANGE_RATE_CHANGE';
export const CURRENCY_SKELETON_USER_CURRENCIES_TABLE_ROWS = 12;
export const CURRENCY_SKELETON_FORM_ROWS = 3;
export const CURRENCY_SKELETON_RATE_TABLE_ROWS = 17;

export const ACCOUNT_DATA_MONTH_COUNT = 6;
export const ACCOUNT_DATA_SKELETON_PLOT_BARS = 6;
export const ACCOUNT_DATA_SKELETON_TABLE_ROWS = 16;

export const TRANSACTIONS_HISTORY_MONTH_COUNT = 12;
export const TRANSACTIONS_HISTORY_TABLE_ROWS_COUNT = 25;
export const TRANSACTIONS_HISTORY_SKELETON_PLOT_BARS = 12;
export const TRANSACTIONS_HISTORY_SKELETON_TABLE_ROWS_COUNT = 16;

export const AUTH_MIN_LOGIN_LENGTH = 6;
export const AUTH_MIN_PASSWORD_LENGTH = 6;
